---
# tasks file for AppService

- set_fact:
    container_names: "{{ teams|subelements('mentors') | union(teams|subelements('trainees')) }}"
  tags: always

- name: Print vars
  debug:
    var: vars

- name: Add deployment configuration
  kubernetes.core.k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: "{{ ansible_operator_meta.name }}-{{ item.1.replace('@', '-') }}"
        namespace: '{{ ansible_operator_meta.namespace }}'
      spec:
        replicas: "{{ size }}"
        selector:
          matchLabels:
            app: appservice
        template:
          metadata:
            labels:
              app: appservice
          spec:
            containers:
            - name: appservice
              command:
              - sleep
              - "6"
              image: "docker.io/library/busybox:latest"
  loop: "{{ container_names }}"
